# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Black-Scholes via AD
#'
#' This example illustrate how to use automatic differentiation to
#' calculate the delte of a Black-Scholes call and put. It is based
#' on the same example in the FastAD sources.
#' @return No value is returned as the function prints to stdout
#' @examples
#' black_scholes_example()
black_scholes_example <- function() {
    invisible(.Call('_RcppFastAD_black_scholes_example', PACKAGE = 'RcppFastAD'))
}

