# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Black-Scholes via AD
#'
#' This example illustrate how to use automatic differentiation to
#' calculate the delte of a Black-Scholes call and put. It is based
#' on the same example in the FastAD sources.
#' @return A matrix with rows for the call and put variant, and columns
#' for option value, delta and vega
#' @examples
#' black_scholes_example()
black_scholes <- function(spot = 105, strike = 100, vol = 5, r = 1.25 / 100, tau = 30.0 / 365) {
    .Call('_RcppFastAD_black_scholes', PACKAGE = 'RcppFastAD', spot, strike, vol, r, tau)
}

